name: CI Pipeline  # pipe line name
# Event when workfow trigger
on:
  push:
    branches:
      - main

build:
  run-on: ubuntu:latest

  steps:
   -uses: action/checkout@v4
   -uses: action/setup-node@v4
   with:
    node-version:20

   -run: npm install 
   -run: npm run build
  
